---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'


inputs:
  - name: mlb-api-repo

outputs:
  - name: build-output

run:
  path: mlb-api-repo/ci/tasks/build.sh